version: 1.0

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

workflows:
  version: 2
  b-a-t:
    jobs:
    - build
    - test:
        requires: 
          - build
    - analyze:
        requires:
          - test

